<?php

namespace UtiliBundle\Repository;

/**
 * UtilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilRepository extends \Doctrine\ORM\EntityRepository
{
}
